Repository DMU-MoonRabbit/MoonRabbit-Web, pull requests merged in 2025-05, with the labels that each got.

#15 [feat] 메인 페이지 구현
  package-lock.json
  package.json
  public/images/ConcernBackground.png
  public/images/MoonRabbitLogo.png
  public/images/MoonRabbitSleep.png
  public/images/MoonRabbitSleep2.png
  public/images/MoonRabbitStars.png
  public/images/MoonRabbitWakeUp.png
  src/App.tsx
  src/assets/images/ConcernBackground.png
  src/assets/images/MoonRabbitLogo.png
  src/assets/images/MoonRabbitSleep2.png
  src/assets/images/MoonRabbitStar.png
  src/assets/images/MoonRabbitStars.png
  src/assets/images/MoonRabbitWakeUp.png
  src/components/CategoryBar.tsx
  src/components/ConcernCard.tsx
  src/components/ConcernSection.tsx
  src/components/Footer.tsx
  src/components/Logo.tsx
  src/components/ServiceExplainCard.tsx
  src/components/ServiceExplainSection.tsx
  src/components/ServiceIntro.tsx
  src/components/TalkSection.tsx
  src/index.css
  src/pages/MainPage.tsx
  src/types/images.d.ts
  yarn.lock
Labels: 😺 도현, 👾 feat

#14 [feat] 로그인, 회원가입 페이지 UI 추가
  .yarn/install-state.gz
  src/App.tsx
  src/assets/images/GoogleLogin.svg
  src/assets/images/KakaoLogin.png
  src/assets/react.svg
  src/assets/vite.svg
  src/components/Login.tsx
  src/pages/LoginSignupPage.tsx
  src/stores/useAuthStore.ts
  src/stores/useUserStore.ts
Labels: 🦊 수현, 👾 feat

#19 [docs] 리드미 추가
  README.md
Labels: 📜 docs, 😺 도현
