Repository DMU-MoonRabbit/MoonRabbit-Web, pull requests merged in 2025-06, with the labels that each got.

#26 [feat] 회원가입, 로그인 API 연동 완료
  package-lock.json
  package.json
  src/assets/images/MoonRabbitStarsDark.png
  src/components/Login.tsx
  src/pages/LoginSignupPage.tsx
  src/stores/useUserStore.ts
  yarn.lock
Labels: 🦊 수현, 👾 feat

#27 [feat] 게시글 API 연동
  package-lock.json
  src/components/CreateConcernModal.tsx
  src/stores/useAnonymousStore.ts
Labels: 😺 도현, 👾 feat

#29 [fix] 게시글 생성 오류 해결
  src/components/CreateConcernModal.tsx
Labels: 🐛 fix, 😺 도현

#32 [feat] 게시글 조회 API 연동
  src/components/ConcernCard.tsx
  src/components/ConcernPost.tsx
  src/pages/NightSkyDetailPage.tsx
  src/pages/NightSkyPage.tsx
  src/stores/useBoardDetailStore.ts
  src/stores/useConcernStore.ts
Labels: 😺 도현, 👾 feat

#33 [feat] 고민 상세 게시판 댓글 및 AI 답변 API 연동
  src/components/CommentInput.tsx
  src/components/CommentItem.tsx
  src/components/ConcernComment.tsx
  src/components/ConcernPost.tsx
  src/components/CreateConcernModal.tsx
  src/pages/NightSkyDetailPage.tsx
  src/stores/useCommentStore.ts
  src/stores/useConcernStore.ts
Labels: 🦊 수현, 👾 feat

#36 [refactor] 전체 코드 리팩토링
  .yarn/install-state.gz
  index.html
  package.json
  src/App.tsx
  src/components/CategoryBar.tsx
  src/components/CommentInput.tsx
  src/components/CommentItem.tsx
  src/components/ConcernCard.tsx
  src/components/ConcernComment.tsx
  src/components/ConcernPost.tsx
  src/components/ConcernSection.tsx
  src/components/CreateConcernButton.tsx
  src/components/CreateConcernModal.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Login.tsx
  src/components/Logo.tsx
  src/components/ServiceExplainCard.tsx
  src/components/ServiceExplainSection.tsx
  src/components/ServiceIntro.tsx
  src/components/TalkSection.tsx
  src/index.css
  src/main.tsx
  src/pages/LoginLoadingPage.tsx
  src/pages/LoginSignupPage.tsx
  src/pages/MainPage.tsx
  src/pages/NightSkyDetailPage.tsx
  src/pages/NightSkyPage.tsx
  src/stores/useAnonymousStore.ts
  src/stores/useAuthStore.ts
  src/stores/useBoardDetailStore.ts
  src/stores/useCommentStore.ts
  src/stores/useConcernDetailStore.ts
  src/stores/useConcernStore.ts
  src/stores/useResponsiveStore.ts
  src/stores/useUserStore.ts
  src/test.ts
  src/types/images.d.ts
  src/vite-env.d.ts
  yarn.lock
Labels: ♻️ refactor, 😺 도현

#38 [cicd] 배포 자동화 파일 생성
  build.sh
Labels: ⚙️ setting, 😺 도현

#43 [fix] 밤하늘 페이지 ux 개선
  src/pages/NightSkyPage.tsx
  src/stores/useConcernStore.ts
Labels: ♻️ refactor, 🐛 fix, 😺 도현
